# netlify.toml
[build]
publish = "public"  # This tells Netlify where your built (static) files are located
command = "# no build command needed for plain HTML/CSS/JS" # No specific build command for static sites

[functions]
directory = "netlify/functions" # Placeholder for serverless functions, even if not used immediately

# Optional: If you want friendly URLs (e.g., /about instead of /about.html)
[[redirects]]
from = "/about"
to = "/about.html"
status = 200
[[redirects]]
from = "/blog"
to = "/blog.html"
status = 200
[[redirects]]
from = "/case-studies"
to = "/case-studies.html"
status = 200
[[redirects]]
from = "/contact"
to = "/contact.html"
status = 200
[[redirects]]
from = "/privacy-policy"
to = "/privacy-policy.html"
status = 200
[[redirects]]
from = "/services"
to = "/services.html"
status = 200
[[redirects]]
from = "/terms-of-service"
to = "/terms-of-service.html"
status = 200
# Also add a redirect for the root to index.html if you want clean URLs
[[redirects]]
from = "/"
to = "/index.html"
status = 200